// Copyright 2026 Carnegie Mellon University. All Rights Reserved.
// Released under a MIT (SEI)-style license. See LICENSE.md in the project root for license information.

/**
 * The SignalR surface of `vm.api`, read out of its C# source.
 *
 * `vm.api` used to publish `contracts/signalr-contract.json` — a snapshot of every hub method it declared
 * and every message it broadcast, generated by a test that reflected over the hub types — and the specs in
 * `tests/contract` asserted the browser clients against that file. It is gone, and it is not coming back,
 * so the choice is between deriving the same surface here and having no cross-repository check at all.
 *
 * The trade that makes: reflection saw the real thing, and this is a scanner over text. It is therefore
 * wrong in one of two ways, and only one of them is acceptable. Reading *less* than the source declares is
 * not: a hub method this misses is a method `signalr-contract.spec.ts` will not check a client against, and
 * the spec passes because it compared against a set nobody read. So everything here fails loudly rather
 * than returning a short answer — an unresolvable method name, an ambiguous hub, a construct the masker was
 * not written for, all throw. Reading *more* is survivable: a phantom method makes a spec fail, somebody
 * looks, and the reader gets fixed.
 *
 * `contract-reader.spec.ts` holds the fixtures for every rule below. Read them as this reader's contract.
 *
 * Nothing here writes to an application repository. `../AGENTS.md` allows reading app source to verify a
 * contract and nothing else, and these helpers only ever read.
 */

import fs from 'fs';
import path from 'path';
import { AppSources, bracketContents, commaItems } from './contract-sources';

/** A hub method a client may invoke. `arguments` is what a *client* passes — see {@link csharpMembers}. */
export type ApiHubMethod = { name: string; arguments: number };

/** A message the API sends, with every argument count it is ever sent with. */
export type ApiHubBroadcast = { name: string; arguments: number[] };

/** One mapped hub: everything the API declares about it. */
export type ApiHub = {
  /** The last segment of the path, which is what the old contract file called the hub. */
  name: string;
  path: string;
  hubType: string;
  /** Repository-relative, so a failure message can name the file to open. */
  file: string;
  methods: ApiHubMethod[];
  broadcasts: ApiHubBroadcast[];
};

// --- Masking ---------------------------------------------------------------------------------------

/**
 * The source with comments removed and every string's and character literal's contents blanked out, so a
 * brace inside a comment or a quoted `)` cannot be mistaken for structure. The result is the same length
 * as the input, so an index into it indexes the original.
 *
 * This is a second masker rather than a reuse of the TypeScript one in `contract-sources.ts` because two
 * of C#'s string forms would defeat it. A verbatim string (`@"C:\vms"`) does not honour `\` as an escape,
 * and doubles its quotes to escape them (`@"say ""hi"""`) — a TypeScript masker reads the first `"` of that
 * pair as the end of the string and the second as the start of a new one, and from there every quote in the
 * file is inverted. What that produces is not an error, it is a hub method name read out of what used to be
 * code.
 */
export function maskCSharp(source: string): string {
  // C# 11 raw string literals would need their own state, and getting them wrong inverts the quoting of
  // the rest of the file rather than failing. There are none in `vm.api` today; this is here so that the
  // day somebody adds one, the contract specs stop with this sentence instead of quietly misreading.
  if (source.includes('"""')) {
    throw new Error(
      'This source holds a raw string literal (`"""`), which maskCSharp does not implement. Reading on ' +
        'would mask the rest of the file wrongly, so it stops here.'
    );
  }

  const out = source.split('');
  let mode: 'code' | 'line' | 'block' | 'string' | 'verbatim' | 'char' = 'code';

  const blank = (i: number) => {
    if (out[i] !== '\n') out[i] = ' ';
  };

  for (let i = 0; i < out.length; i++) {
    const c = out[i];

    if (mode === 'line') {
      if (c === '\n') mode = 'code';
      else blank(i);
      continue;
    }

    if (mode === 'block') {
      if (c === '*' && out[i + 1] === '/') {
        out[i] = ' ';
        out[i + 1] = ' ';
        i++;
        mode = 'code';
      } else {
        blank(i);
      }
      continue;
    }

    if (mode === 'string' || mode === 'char') {
      const quote = mode === 'string' ? '"' : "'";

      if (c === '\\') {
        out[i] = ' ';
        // Bounded, so a trailing backslash cannot break the "same length as the input" invariant that
        // every caller indexes against.
        if (i + 1 < out.length) out[i + 1] = ' ';
        i++;
      } else if (c === quote) {
        mode = 'code';
      } else {
        blank(i);
      }
      continue;
    }

    if (mode === 'verbatim') {
      if (c === '"' && out[i + 1] === '"') {
        // An escaped quote, not the end. Blanking both is what keeps the following code readable.
        out[i] = ' ';
        out[i + 1] = ' ';
        i++;
      } else if (c === '"') {
        mode = 'code';
      } else {
        blank(i);
      }
      continue;
    }

    if (c === '/' && out[i + 1] === '/') {
      out[i] = ' ';
      out[i + 1] = ' ';
      i++;
      mode = 'line';
      continue;
    }

    if (c === '/' && out[i + 1] === '*') {
      out[i] = ' ';
      out[i + 1] = ' ';
      i++;
      mode = 'block';
      continue;
    }

    // `@"…"`, `$"…"`, `$@"…"` and `@$"…"` are all legal, so the prefix is read as a run. Interpolated
    // strings matter as much as verbatim ones: `$"{_pathbase}/hubs/vm"` holds braces, and an unblanked
    // brace closes a class body early and takes every member after it out of the reader's view.
    if (c === '@' || c === '$') {
      let j = i;
      let verbatim = false;

      while (out[j] === '@' || out[j] === '$') {
        verbatim = verbatim || out[j] === '@';
        j++;
      }

      if (out[j] === '"') {
        mode = verbatim ? 'verbatim' : 'string';
        i = j;
      }
      continue;
    }

    if (c === '"') {
      mode = 'string';
      continue;
    }

    if (c === "'") {
      mode = 'char';
      continue;
    }
  }

  return out.join('');
}

// --- Members ---------------------------------------------------------------------------------------

/** A method or constructor declaration found in a C# source. */
export type CsharpMember = {
  name: string;
  /** The modifiers and return type in front of the name, as written. */
  prefix: string;
  /** Parameters as written, in order. Positional, so a caller's arguments can be lined up against them. */
  parameters: string[];
  /** Offset of the `(` that opens the parameter list. */
  at: number;
  /** Half-open range of the body, or null for an expression-bodied or abstract member. */
  body: [number, number] | null;
};

const ACCESS = /\b(?:public|private|protected|internal)\b/;

/** Characters that end the statement or member before the one starting here. */
const BOUNDARY = ';{}';

/**
 * Every method and constructor declared in `masked`, found by looking backwards from each `name(`.
 *
 * Backwards, rather than by matching a signature forwards, because a C# signature is not a shape a regex
 * can be trusted with: the return type may be generic, nullable, an array, or a namespace-qualified name,
 * and a pattern loose enough for all of those also matches half the call sites in the file. What a
 * declaration does have is an access modifier between the previous `;`/`{`/`}` and its name, and a call
 * never does.
 */
export function csharpMembers(masked: string): CsharpMember[] {
  const found: CsharpMember[] = [];

  for (const match of masked.matchAll(/(\w+)\s*\(/g)) {
    const open = match.index + match[0].length - 1;
    let start = match.index - 1;

    while (start >= 0 && !BOUNDARY.includes(masked[start])) start--;

    const prefix = masked.slice(start + 1, match.index);

    if (!ACCESS.test(prefix)) {
      continue;
    }

    const [from, to] = bracketContents(masked, open);
    let after = to + 1;
    while (after < masked.length && /\s/.test(masked[after])) after++;

    // A declaration is followed by its body, by `=>`, or by `;`. Anything else is a call whose prefix
    // happened to hold an access modifier — a field initialiser calling a factory, most often.
    const bodied = masked[after] === '{';
    if (!bodied && masked[after] !== ';' && masked.slice(after, after + 2) !== '=>') {
      continue;
    }

    found.push({
      name: match[1],
      prefix: prefix.trim(),
      parameters: commaItems(masked, from, to).map(([a, b]) => masked.slice(a, b).trim()),
      at: open,
      body: bodied ? bracketContents(masked, after) : null,
    });
  }

  return found;
}

/** The half-open range of a class body. */
export function classBody(masked: string, className: string): [number, number] {
  const declaration = new RegExp(`\\bclass\\s+${className}\\b`).exec(masked);

  if (!declaration) {
    throw new Error(`No 'class ${className}' declaration in this source.`);
  }

  const open = masked.indexOf('{', declaration.index);

  if (open < 0) {
    throw new Error(`The declaration of '${className}' has no body.`);
  }

  return bracketContents(masked, open);
}

/**
 * The methods a SignalR client can invoke on a hub class.
 *
 * SignalR exposes every public instance method declared on the hub type, which is why this does not look
 * for `Task`: a hub method that returned `void` would be just as invocable, and a reader that only
 * recognised `Task` would leave it unchecked. Excluded are the constructor (not invocable), `static`
 * members (not invocable) and `override`s — `OnDisconnectedAsync` and friends are declared on `Hub`, and
 * SignalR does not dispatch to methods it inherits.
 *
 * `arguments` is the count a *client* sends, which is the parameter count less a `CancellationToken`:
 * SignalR binds that one itself from the connection, and a client that passed one would be invoking a
 * method with one argument too many.
 */
export function hubMethods(source: string, className: string): ApiHubMethod[] {
  const masked = maskCSharp(source);
  const [from, to] = classBody(masked, className);

  return csharpMembers(masked)
    .filter((member) => member.at > from && member.at < to)
    .filter((member) => /\bpublic\b/.test(member.prefix))
    .filter((member) => !/\b(?:static|override)\b/.test(member.prefix))
    .filter((member) => member.name !== className)
    .map((member) => ({
      name: member.name,
      arguments: member.parameters.filter((x) => !/\bCancellationToken\b/.test(x)).length,
    }));
}

/**
 * The auto-property names of a class: `public X Y { get; set; }` and nothing else.
 *
 * "And nothing else" is the point. Entity Framework reports a modification against a property it tracks,
 * and what it tracks is the settable scalars; a computed getter (`public bool DefaultUrl { get => … }`) can
 * never be reported because nothing can set it, and a `virtual` navigation property is tracked as a
 * relationship rather than as a value. Including either would put a name into the modified-properties
 * check that the API cannot send, and the check would fail on the reader's mistake.
 *
 * A restricted setter (`{ get; private set; }`) does count. EF sets those through the backing field and
 * reports them like any other, and leaving them out would be the more dangerous mistake of the two: a name
 * the API can send that the modified-properties check never looks for.
 */
export function autoProperties(source: string, className: string): string[] {
  const masked = maskCSharp(source);
  const [from, to] = classBody(masked, className);
  const pattern =
    /\bpublic\s+((?:(?:virtual|static|override|new|abstract|sealed|required)\s+)*)([\w.<>,\[\]?]+)\s+(\w+)\s*\{\s*get\s*;\s*(?:(?:private|protected|internal)\s+)*set\s*;\s*\}/g;

  return [...masked.slice(from, to).matchAll(pattern)]
    .filter((match) => !/\b(?:virtual|static)\b/.test(match[1]))
    .map((match) => match[3]);
}

// --- Broadcasts ------------------------------------------------------------------------------------

/** A `Clients.…SendAsync(…)` call: the hub it goes out on, the message name, and the client's arity. */
export type ApiHubSend = { hubType: string; name: string; arguments: number };

/** `public const string X = "Y";` declarations, keyed as `Class.X`. */
export function constantStrings(source: string): Map<string, string> {
  const masked = maskCSharp(source);
  const found = new Map<string, string>();

  for (const declaration of masked.matchAll(/\bclass\s+(\w+)/g)) {
    const [from, to] = classBody(masked, declaration[1]);

    for (const match of masked.slice(from, to).matchAll(/\bconst\s+string\s+(\w+)\s*=\s*"/g)) {
      // Out of the original: the mask blanked what the quotes hold.
      const at = from + match.index + match[0].length;
      const value = /^([^"]*)"/.exec(source.slice(at))?.[1];

      if (value === undefined) {
        throw new Error(`The constant '${declaration[1]}.${match[1]}' has no terminated string value.`);
      }

      found.set(`${declaration[1]}.${match[1]}`, value);
    }
  }

  return found;
}

/** True when an argument is the `CancellationToken` overload's, which is not sent to any client. */
function isCancellationToken(argument: string): boolean {
  return /\bCancellationToken\b/.test(argument) || /\b(?:cancellationToken|ct)\b/.test(argument);
}

/**
 * Every message a source sends to clients, with the arity each is sent with.
 *
 * Only `SendAsync` calls whose receiver mentions `Clients` count. `SendAsync` is also `HttpClient`'s method
 * and a dataflow block's, and `vm.api` calls both — a reader that matched on the name alone would report
 * an outbound webhook as a hub broadcast.
 *
 * The hub a send belongs to comes from the file: the `IHubContext<T>` it holds, or the hub class it is
 * inside. A file naming two different hubs throws rather than guessing, because guessing wrong here moves
 * a message from one hub's contract to another's and both specs still pass.
 */
export function hubSends(
  source: string,
  constants: Map<string, string>,
  enclosingHubType?: string
): ApiHubSend[] {
  const masked = maskCSharp(source);
  const contexts = [...new Set([...masked.matchAll(/IHubContext<\s*(\w+)\s*>/g)].map((x) => x[1]))];
  const members = csharpMembers(masked);
  const found: ApiHubSend[] = [];

  for (const match of masked.matchAll(/\.SendAsync\s*(?:<[^<>()]*>\s*)?\(/g)) {
    const open = match.index + match[0].length - 1;
    let start = match.index;
    while (start >= 0 && !BOUNDARY.includes(masked[start])) start--;

    if (!/\bClients\b/.test(masked.slice(start + 1, match.index))) {
      continue;
    }

    const hubTypes = [...new Set([...contexts, ...(enclosingHubType ? [enclosingHubType] : [])])];

    if (hubTypes.length !== 1) {
      throw new Error(
        hubTypes.length === 0
          ? 'A SendAsync to Clients was found in a source that names no hub, so the hub it goes out on ' +
            'cannot be read.'
          : `A SendAsync to Clients was found in a source naming more than one hub (${hubTypes}), so ` +
            'the hub it goes out on cannot be read. This reader needs to attribute by receiver.'
      );
    }

    const [from, to] = bracketContents(masked, open);
    const items = commaItems(masked, from, to).map(([a, b]) => ({
      text: masked.slice(a, b).trim(),
      original: source.slice(a, b).trim(),
    }));

    if (items.length === 0) {
      throw new Error('A SendAsync to Clients names no message.');
    }

    const rest = items.slice(1);
    const args = rest.length - (rest.length > 0 && isCancellationToken(rest[rest.length - 1].text) ? 1 : 0);

    for (const name of resolveMessageNames(items[0], masked, source, members, open, constants)) {
      found.push({ hubType: hubTypes[0], name, arguments: args });
    }
  }

  return found;
}

/**
 * The message name(s) one send can carry.
 *
 * Three forms, in order of how much work they are. A string literal is itself. `VmHubMethods.VmCreated` is
 * a constant, looked up in the table the caller built across the whole application. And a bare identifier
 * that is a *parameter of the enclosing method* is resolved through that method's call sites in the same
 * file — which is not generality for its own sake: `VmBaseSignalRHandler.HandleCreateOrUpdate` takes the
 * message name as a `string method` parameter and is how both `VmCreated` and `VmUpdated` are sent, so a
 * reader without this rule would miss the two broadcasts the VM list is built on.
 *
 * Anything else throws. A send whose name could not be read is a broadcast missing from the surface, and a
 * broadcast missing from the surface is a client handler that nothing checks.
 */
function resolveMessageNames(
  first: { text: string; original: string },
  masked: string,
  source: string,
  members: CsharpMember[],
  at: number,
  constants: Map<string, string>
): string[] {
  const literal = /^"/.test(first.text) ? /^"([^"]*)"/.exec(first.original)?.[1] : undefined;

  if (literal !== undefined) {
    return [literal];
  }

  if (constants.has(first.text)) {
    return [constants.get(first.text)];
  }

  if (/^\w+$/.test(first.text)) {
    const enclosing = members
      .filter((member) => member.body && at > member.body[0] && at < member.body[1])
      .sort((a, b) => b.body[0] - a.body[0])[0];

    const index = enclosing?.parameters.findIndex((parameter) =>
      new RegExp(`\\b${first.text}$`).test(parameter)
    );

    if (enclosing && index >= 0) {
      const names = new Set<string>();

      for (const call of masked.matchAll(new RegExp(`\\b${enclosing.name}\\s*\\(`, 'g'))) {
        const open = call.index + call[0].length - 1;

        if (open === enclosing.at) {
          continue;
        }

        const [from, to] = bracketContents(masked, open);
        const argument = commaItems(masked, from, to)[index];

        if (!argument) {
          throw new Error(
            `A call to '${enclosing.name}' passes no argument for the message-name parameter ` +
              `'${first.text}', so the message it sends cannot be read.`
          );
        }

        for (const name of resolveMessageNames(
          { text: masked.slice(...argument).trim(), original: source.slice(...argument).trim() },
          masked,
          source,
          members,
          open,
          constants
        )) {
          names.add(name);
        }
      }

      if (names.size > 0) {
        return [...names];
      }
    }
  }

  throw new Error(
    `A SendAsync names its message as '${first.text}', which is neither a string literal, nor a ` +
      'constant this reader found, nor a parameter resolvable from call sites in the same file. The ' +
      'message it sends is therefore unknown, and a broadcast nobody knows about is a client handler ' +
      'nobody checks.'
  );
}

// --- The application on disk -----------------------------------------------------------------------

/** The application project directory, which is what everything below is read out of. */
export function apiProjectDirectory(): string {
  return path.join(AppSources.vmApi(), 'src', 'Player.Vm.Api');
}

function csharpFiles(directory: string): string[] {
  return fs
    .readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const full = path.join(directory, entry.name);

      if (entry.isDirectory()) {
        return entry.name === 'obj' || entry.name === 'bin' ? [] : csharpFiles(full);
      }

      return entry.name.endsWith('.cs') ? [full] : [];
    })
    .sort();
}

/** Every hub the application maps, as the type it maps and the path it maps it at. */
export function mappedHubs(source: string): Array<{ hubType: string; path: string }> {
  const masked = maskCSharp(source);

  return [...masked.matchAll(/\bMapHub\s*<\s*(\w+)\s*>\s*\(/g)].map((match) => {
    const open = match.index + match[0].length - 1;
    const [from, to] = bracketContents(masked, open);
    const [first] = commaItems(masked, from, to);
    const hubPath = /^\s*"([^"]*)"/.exec(source.slice(...first))?.[1];

    if (!hubPath) {
      throw new Error(
        `MapHub<${match[1]}> is mapped at something other than a string literal, so the path clients ` +
          'must dial cannot be read.'
      );
    }

    return { hubType: match[1], path: hubPath };
  });
}

/** The namespaces a source imports, which is how a hub type name is resolved to one file. */
function importedNamespaces(source: string): string[] {
  return [...maskCSharp(source).matchAll(/^\s*using\s+(?:static\s+)?([\w.]+)\s*;/gm)].map((x) => x[1]);
}

/**
 * The file holding the hub class a `MapHub<T>` names.
 *
 * `vm.api` holds two classes called `VmHub` — `Features/Vms/Hubs/VmHub.cs`, which is the one in use, and
 * `Hubs/VmHub.cs`, a 2022 copy with its own `JoinView`/`LeaveView` that is mapped nowhere. Picking by name
 * alone is a coin toss between a hub with ten methods and one with two, and losing it silently deletes
 * eight methods from the surface. So the tie is broken the way the compiler breaks it: by which namespace
 * the file that calls `MapHub` imports.
 */
function resolveHubFile(files: string[], hubType: string, imported: string[]): string {
  const declares = new RegExp(`\\bclass\\s+${hubType}\\b[^{]*:\\s*Hub\\b`);
  const candidates = files.filter((file) => declares.test(maskCSharp(fs.readFileSync(file, 'utf8'))));

  if (candidates.length === 1) {
    return candidates[0];
  }

  if (candidates.length === 0) {
    throw new Error(`MapHub<${hubType}> names a hub type no source in the project declares.`);
  }

  const inScope = candidates.filter((file) => {
    const namespace = /^\s*namespace\s+([\w.]+)/m.exec(fs.readFileSync(file, 'utf8'))?.[1];

    return namespace && imported.includes(namespace);
  });

  if (inScope.length !== 1) {
    throw new Error(
      `${candidates.length} sources declare a hub called ${hubType} (${candidates.join(', ')}) and ` +
        `${inScope.length} of them are in a namespace the mapping file imports, so which one is mapped ` +
        'cannot be read.'
    );
  }

  return inScope[0];
}

/** True when the application source needed to derive the surface is checked out. */
export function apiSourcesPresent(): boolean {
  return fs.existsSync(path.join(apiProjectDirectory(), 'Startup.cs'));
}

/**
 * Everything the API declares about every hub it maps, read from the project on disk.
 *
 * Ordered by path so a failure message reads the same on every machine.
 */
export function apiHubSurface(): ApiHub[] {
  const project = apiProjectDirectory();
  const startupFile = path.join(project, 'Startup.cs');
  const startup = fs.readFileSync(startupFile, 'utf8');
  const files = csharpFiles(project);
  const imported = importedNamespaces(startup);

  // Built across the whole project, because the handlers that send `VmHubMethods.VmCreated` are not in the
  // file that declares it. Two classes of the same name with the same values are fine — the duplicate
  // `VmHubMethods` beside the duplicate hub declares three of the same five — but a *conflict* is a real
  // hazard worth stopping for: it means one of the two copies has drifted and half the application is
  // sending a name the other half does not know.
  const constants = new Map<string, string>();

  for (const file of files) {
    for (const [key, value] of constantStrings(fs.readFileSync(file, 'utf8'))) {
      if (constants.has(key) && constants.get(key) !== value) {
        throw new Error(
          `Two declarations of the constant '${key}' disagree: '${constants.get(key)}' and '${value}'. ` +
            'One of them is dead code and the other is the contract, and this reader cannot tell which.'
        );
      }

      constants.set(key, value);
    }
  }

  const hubs = mappedHubs(startup).map((mapped) => {
    const file = resolveHubFile(files, mapped.hubType, imported);

    return {
      ...mapped,
      name: mapped.path.split('/').filter(Boolean).pop(),
      file: path.relative(AppSources.vmApi(), file),
      hubFile: file,
      methods: hubMethods(fs.readFileSync(file, 'utf8'), mapped.hubType),
    };
  });

  const sends: ApiHubSend[] = [];

  for (const file of files) {
    const source = fs.readFileSync(file, 'utf8');
    const enclosing = hubs.find((hub) => hub.hubFile === file);

    sends.push(...hubSends(source, constants, enclosing?.hubType));
  }

  return hubs
    .map(({ hubFile, ...hub }) => ({
      ...hub,
      broadcasts: [...new Set(sends.filter((x) => x.hubType === hub.hubType).map((x) => x.name))]
        .sort()
        .map((name) => ({
          name,
          arguments: [
            ...new Set(
              sends.filter((x) => x.hubType === hub.hubType && x.name === name).map((x) => x.arguments)
            ),
          ].sort((a, b) => a - b),
        })),
    }))
    .sort((a, b) => a.path.localeCompare(b.path));
}

// --- The VM the browser indexes --------------------------------------------------------------------

/** `TitleCase` to `camelCase`, which is what the API does to a property name before it sends it. */
export function camelCase(name: string): string {
  return `${name[0].toLowerCase()}${name.slice(1)}`;
}

/**
 * Every property name `VmUpdated`'s `modifiedProperties` can carry.
 *
 * The list comes from the *domain entity*, not from the DTO: `VmUpdatedSignalRHandler` sends
 * `notification.ModifiedProperties.Select(x => x.TitleCaseToCamelCase())`, and those names are Entity
 * Framework's — the properties it tracks on `Domain/Models/Vm.cs`. The client then spends them against the
 * serialized DTO (`model[x] = vm[x]`), so the two lists meeting is the whole contract.
 */
export function domainVmModifiedProperties(): string[] {
  const file = path.join(apiProjectDirectory(), 'Domain', 'Models', 'Vm.cs');

  return autoProperties(fs.readFileSync(file, 'utf8'), 'Vm').map(camelCase).sort();
}

/** The JSON keys of the `Vm` the API sends, from the view model the hub and the controllers both map to. */
export function viewModelVmProperties(): string[] {
  const file = path.join(apiProjectDirectory(), 'Features', 'Vms', 'Models', 'Vm.cs');

  return autoProperties(fs.readFileSync(file, 'utf8'), 'Vm').map(camelCase).sort();
}
